version: '3.9'
services:
  db:
    image: postgres
    container_name: "users_db"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: users

  minio:
    image: 'minio/minio'
    container_name: 'minio'
    ports:
      - '9000:9000'
      - '9001:9001'
      
    volumes:
      - miniodata:/var/lib/minio/data
    environment:
      MINIO_ROOT_USER: '${S3_MINIO_ROOT_USER}'
      MINIO_ROOT_PASSWORD: '${S3_MINIO_ROOT_PASSWORD}'
      MINIO_HTTP_TLS_CERT_FILE: ''
      MINIO_HTTP_TLS_KEY_FILE: ''
    command: server --console-address ":9001" /data

volumes:
  miniodata:
    driver: local