version: '3.9'
services:
  db:
    image: postgres
    container_name: "users_db"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: users